### ISSUE TITLE
Fix stereo files to mono

### ISSUE THREAD

**Issue by Mte90** [common-voice/cv-dataset#1]
As reference https://github.com/mozilla/CorporaCreator/issues/110

**Comment by phirework** [comment]
Thanks for moving this here!

> So this generator don't check if the files are mono or not before package it?

To continue the conversation from that thread, no there currently is no real QA on the mp3 files during the bundling process. This past release we've added checking for file sizes smaller than 256bytes to eliminate totally blank files submitted due to some mechanical/hardware error, but that's about it. Rather than skipping stereo files entirely I'd like to figure out why the site is now sending audio in stereo, and convert the ones that are currently a problem.

**Comment by Mte90** [comment]
We convert them so maybe a check during the generation for those files?
Maybe they was generated in a specific period of time.

**Comment by dag7dev** [comment]
Do you need a batch or a live real-time implementation of mono recordings / "conversion"?

**Comment by Mte90** [comment]
I think that just a batch conversion, so they can release the dataset in the right way.

**Comment by phirework** [comment]
Hello! We ran a conversion along with the [latest dataset release](commonvoice.mozilla.org/datasets) and everything in Corpus 6 should be mono audio. I'm going to close this, let me know if you run into other issues.
