### ISSUE TITLE
Script to download all the datasets

### ISSUE THREAD

**Issue by harrygcoppock** [common-voice/cv-dataset#5]
Hi,

Love the dataset.

I was wondering if there was a script to download all the datasets for all languages?

Cheers

**Comment by phirework** [comment]
Hi there, there's currently no script available due to resourcing limitations. It woud be challengingt to roll your own because for legal reasons Mozilla needs to keep track of the emails of everyone who downloads the dataset, and for traffic reasons each dataset link has tokens attached that expire after 12 hours, so such a script would need to be integrated with the Common Voice API in the core repo as well, but we're happy to accept PRs that do something like this.
